import marimo

__generated_with = "0.20.4"
app = marimo.App()


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Master Equation Solver: Single-Qubit Dynamics

    Authors: J.R. Johansson and P.D. Nation

    Modified by: C. Staufebiel (2022)

    ### Introduction
    In this notebook we will explore the dynamics of a single-qubit interacting with an environment. The evolution of the qubit state is governed by the Master equation. We will make use of the master equation solver `qutip.mesolve` implemented in qutip, to obtain the time-evolution of the qubit for different settings.

    You can read more about the master equation solver (and the theory behind it) in the [QuTiP docs](https://qutip.readthedocs.io/en/latest/guide/dynamics/dynamics-master.html).

    ### Import
    Here we import the required modules for this example.
    """)
    return


@app.cell
def _():
    import matplotlib.pyplot as plt
    import numpy as np
    from qutip import Bloch, about, basis, mesolve, sigmam, sigmax, sigmay, sigmaz

    import matplotlib.figure

    # matplotlib.figure.Figure.show = lambda self, *args, **kwargs: None

    # '%matplotlib inline' command supported automatically in marimo
    return (
        Bloch,
        about,
        basis,
        mesolve,
        np,
        plt,
        sigmam,
        sigmax,
        sigmay,
        sigmaz,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### System setup
    We will start with a basic Hamiltonian for the qubit, which flips the state of the qubit represented by the Pauli Matrix $\sigma_x$.

    $H = \frac{\Delta}{2} \sigma_x$

    Additionally, we add a collapse operator that describes the dissipation of energy from the qubit to an external environment. The collapse operator is defined by

    $C = \sqrt{g} \sigma_z$

    where $g$ is the dissipation coefficient.
    We define the qubit to be in the ground state at $t=0$.
    """)
    return


@app.cell
def _(basis, np, sigmax, sigmaz):
    # coefficients
    delta = 2 * np.pi
    g = 0.25

    # hamiltonian
    H = delta / 2.0 * sigmax()

    # list of collapse operators
    c_ops = [np.sqrt(g) * sigmaz()]

    # initial state
    psi0 = basis(2, 0)

    # times
    tlist = np.linspace(0, 5, 100)
    return H, c_ops, delta, g, psi0, tlist


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Time-evolution
    We pass these definition to the `qutip.mesolve` function. The collapse operators need to be passed in a list (even if there is only one collapse operator). As the fifth argument we pass a list of operators, for which the solver will return the expectation value at the given times in `tlist`. In this example we want to obtain the expectation value for $\sigma_z$.
    """)
    return


@app.cell
def _(H, c_ops, mesolve, psi0, sigmaz, tlist):
    res = mesolve(H, psi0, tlist, c_ops, [sigmaz()])
    return (res,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    For this particular Hamiltonian and dissipation process we can derive the analytical solution for the expectation value of $\sigma_z$.
    """)
    return


@app.cell
def _(g, np, tlist):
    sz_analytic = np.cos(2 * np.pi * tlist) * np.exp(-tlist * g)
    return (sz_analytic,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Comparison to Analytical Solution
    By plotting the expectation value from `mesolve` and the analytical result we can verify the correctness of the result. We can access the expectation value generated by `mesolve` by accessing `result.expect[0]`.
    """)
    return


@app.cell
def _(plt, res, sz_analytic, tlist):
    fig, ax = plt.subplots()

    ax.scatter(tlist, res.expect[0], c="r", marker="x", label="mesolve")
    ax.plot(tlist, sz_analytic, label="Analytic")

    ax.set_xlabel("Time")
    ax.set_ylabel("<sigma_z>")
    ax.legend()

    fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Qubit Dynamics on the Bloch Sphere

    We can also visualise the dynamics of the qubit state on the Bloch sphere. To generate more interesting plots, we consider slightly more complex dynamics of the qubit state.

    ### Rotating State

    Consider the following Hamiltonian:

    $H = \Delta ( \, cos(\theta) \, \sigma_z + sin(\theta) \, \sigma_x  \, )$.

    $\theta$ defines the angle of the qubit state between the $z$-axis toward the $x$-axis. We can again use `mesolve` to obtain the dynamics of the system. Here, we pass an empty list of collapse operators.
    """)
    return


@app.cell
def _(delta, mesolve, np, psi0, sigmax, sigmay, sigmaz):
    # Angle
    theta = 0.2 * np.pi
    H_1 = delta * (np.cos(theta) * sigmaz() + np.sin(theta) * sigmax())
    # Hamiltonian
    tlist_1 = np.linspace(0, 5, 1000)
    # Obtain Time Evolution
    result = mesolve(H_1, psi0, tlist_1, [], [sigmax(), sigmay(), sigmaz()])
    return H_1, result, tlist_1


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can visualise the state on the Bloch sphere by using the `qutip.Bloch` class. We can add points to the Bloch sphere and also vectors representing states.
    """)
    return


@app.cell
def _(Bloch, np, psi0, result):
    # Extract expectation values for pauli matrices
    exp_sx_circ, exp_sy_circ, exp_sz_circ = result.expect
    exp_sx_circ, exp_sy_circ, exp_sz_circ = (np.array(exp_sx_circ), np.array(exp_sy_circ), np.array(exp_sz_circ))
    _sphere = Bloch()
    _sphere.add_points([exp_sx_circ, exp_sy_circ, exp_sz_circ], meth='l')
    _sphere.add_states(psi0)
    # Create Bloch sphere plot
    _sphere.render()
    _sphere.fig
    return exp_sx_circ, exp_sy_circ, exp_sz_circ


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    From the plot we can see the time-evolution of the initial state, which is a circular movement on the sphere's surface. As before, we add some collapse operators to the system, which alter the dynamics of the system.

    ### Qubit dephasing

    To change the phase of the qubit we introduce the following collapse operator:

    $C = \sqrt{\gamma_p} \; \sigma_z$
    """)
    return


@app.cell
def _(Bloch, H_1, mesolve, np, psi0, sigmax, sigmay, sigmaz, tlist_1):
    gamma_phase = 0.5
    c_ops_1 = [np.sqrt(gamma_phase) * sigmaz()]
    result_1 = mesolve(H_1, psi0, tlist_1, c_ops_1, [sigmax(), sigmay(), sigmaz()])
    exp_sx_dephase, exp_sy_dephase, exp_sz_dephase = result_1.expect
    exp_sx_dephase, exp_sy_dephase, exp_sz_dephase = (np.array(exp_sx_dephase), np.array(exp_sy_dephase), np.array(exp_sz_dephase))
    _sphere = Bloch()
    _sphere.add_points([exp_sx_dephase, exp_sy_dephase, exp_sz_dephase], meth='l')
    _sphere.add_states(psi0)
    _sphere.render()
    _sphere.fig
    return exp_sx_dephase, exp_sy_dephase, exp_sz_dephase


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can observe the dephasing of the qubit by the decreasing radius of the qubit state movement.

    ### Qubit relaxation

    Another type of dissipation we can explore is the relaxation of the qubit originating from the collapse operator

    $C = \sqrt{\gamma_r} \sigma_-$

    This induces spontaneous flips of the qubit from the excited state to the ground state with a rate $\gamma_r$. Again we can observe the qubit dynamics on the Bloch sphere.
    """)
    return


@app.cell
def _(Bloch, H_1, mesolve, np, psi0, sigmam, sigmax, sigmay, sigmaz, tlist_1):
    gamma_relax = 0.5
    c_ops_2 = [np.sqrt(gamma_relax) * sigmam()]
    result_2 = mesolve(H_1, psi0, tlist_1, c_ops_2, [sigmax(), sigmay(), sigmaz()])
    exp_sx_relax, exp_sy_relax, exp_sz_relax = result_2.expect
    _sphere = Bloch()
    _sphere.add_points([exp_sx_relax, exp_sy_relax, exp_sz_relax], meth='l')
    _sphere.add_states(psi0)
    _sphere.render()
    _sphere.fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can see how the circular trajectory shifts more to the ground state of the qubit.

    ### Conclusion
    Using the methods above, you can simulate any dissipative quantum system, whose dynamics are described by the master equation. Additionally you can make use of the methods to visualise the dynamics of a qubit state on the Bloch sphere.

    ## About
    """)
    return


@app.cell
def _(about):
    about()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Testing
    """)
    return


@app.cell
def _(
    exp_sx_circ,
    exp_sx_dephase,
    exp_sy_circ,
    exp_sy_dephase,
    exp_sz_circ,
    exp_sz_dephase,
    np,
    res,
    sz_analytic,
):
    assert np.allclose(res.expect[0], sz_analytic, atol=0.05)
    assert np.allclose(exp_sz_circ**2 + exp_sy_circ**2 + exp_sx_circ**2, 1.0)
    assert np.all(
        np.diff(exp_sx_dephase**2 + exp_sy_dephase**2 + exp_sz_dephase**2) <= 0
    )
    return


if __name__ == "__main__":
    app.run()
